# Whatsapp Chat Analysis 
Project Type : NLP

In [50]:
# Import Laibraries

import warnings
warnings.filterwarnings('ignore')

import re # Regular Expression

import pandas as pd # Dataframe

# Load Data :

In [51]:
with open('chat.txt','r',encoding='utf-8') as f:
    data = f.read()

In [52]:
# Regular Expression(regex)
pattern = r'\[\d{1,2}/\d{1,2}/\d{2,4},\s\d{1,2}:\d{2}:\d{2}\s[APap][Mm]\]\s'

In [53]:
messages = re.split(pattern, data)[1:]

In [54]:
dates = re.findall(pattern, data)

In [55]:
df = pd.DataFrame({'user_message':messages, 'message_date':dates})

In [56]:
df['message_date'] = (df['message_date']
                      .str.strip('[] ')
                      .str.replace('\u202f', ' ', regex=False))  # iOS sometimes uses a special space before AM/PM
df['message_date'] = pd.to_datetime(df['message_date'], format='%m/%d/%y, %I:%M:%S %p')

df.rename(columns={'message_date': 'date'}, inplace=True)
df.head()

                                        user_message                date
0  Bhai❤️‍🩹🫂: Waiting for this message. This may ... 2025-09-13 21:29:11
1  Bhai❤️‍🩹🫂: Waiting for this message. This may ... 2025-09-13 21:29:11
2  Bhai❤️‍🩹🫂: Waiting for this message. This may ... 2025-09-13 21:29:35
3  Bhai❤️‍🩹🫂: Waiting for this message. This may ... 2025-09-13 21:38:12
4  Bhai❤️‍🩹🫂: Waiting for this message. This may ... 2025-09-13 21:38:25

In [57]:
# DataFrame Shape
df.shape

(3397, 2)

* **Total Chat Persons(Columns):** 2
* **Total Messages(Records):** 3397

# Data Pre-Processing :

In [58]:
users, msgs = [], []
for m in df['user_message']:
    parts = re.split(r'^([^:]+):\s', m, maxsplit=1)
    if len(parts) > 1:
        users.append(parts[1]); msgs.append(parts[2])
    else:
        users.append('group_notification'); msgs.append(parts[0])
        
df['user'] = users
df['message'] = msgs
df.drop(columns=['user_message'], inplace=True)

df.head(3)

,date,user,message
0,2025-09-13 21:29:11,Bhai❤️‍🩹🫂,Waiting for this message. This may take a whil...
1,2025-09-13 21:29:11,Bhai❤️‍🩹🫂,Waiting for this message. This may take a whil...
2,2025-09-13 21:29:35,Bhai❤️‍🩹🫂,Waiting for this message. This may take a whil...

In [59]:
df['year'] = df['date'].dt.year

In [60]:
df['month'] = df['date'].dt.month_name()

In [61]:
df['day'] = df['date'].dt.day

In [62]:
df['hour'] = df['date'].dt.hour

In [63]:
df['minunte'] = df['date'].dt.minute

In [64]:
df.head(3)

,date,user,message,year,month,day,hour,minunte
0,2025-09-13 21:29:11,Bhai❤️‍🩹🫂,Waiting for this message. This may take a whil...,2025,September,13,21,29
1,2025-09-13 21:29:11,Bhai❤️‍🩹🫂,Waiting for this message. This may take a whil...,2025,September,13,21,29
2,2025-09-13 21:29:35,Bhai❤️‍🩹🫂,Waiting for this message. This may take a whil...,2025,September,13,21,29